version: '3.8'

services:
  postgres:
    container_name: pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: forum
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres

  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    
volumes:
  database:
  cache: